### ISSUE TITLE
failing test: document is not defined

### ISSUE THREAD

**Issue by ahdinosaur** [stackcss/sheetify#77]
offending code [here](https://github.com/stackcss/sheetify/blob/master/test/prefix.js#L43)

```
evalmachine.<anonymous>:8
    var elem = document.createElement('style');
               ^
ReferenceError: document is not defined
    at module.exports (evalmachine.<anonymous>:8:16)
    at Object.2.insert-css (evalmachine.<anonymous>:28:39)
    at s (evalmachine.<anonymous>:1:254)
    at e (evalmachine.<anonymous>:1:425)
    at evalmachine.<anonymous>:1:443
    at ContextifyScript.Script.runInNewContext (vm.js:18:15)
    at Object.exports.runInNewContext (vm.js:49:17)
    at parseBundle (/home/travis/build/stackcss/sheetify/test/prefix.js:43:10)
    at /home/travis/build/stackcss/sheetify/node_modules/browserify/index.js:776:13
    at ConcatStream.<anonymous> (/home/travis/build/stackcss/sheetify/node_modules/concat-stream/index.js:36:43)
```

**Comment by yoshuawuyts** [comment]
ah dammit, think we need to run it either inside `jsdom` or extract the bundle using [css-extract](https://github.com/stackcss/css-extract)

**Comment by ahdinosaur** [comment]
hmm, we're using `css-extract` already, but the `insert-css` calls seem to be unaffected. here's a potential fix to `css-extract`: https://github.com/stackcss/css-extract/pull/6.
